inherit_from:
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/4.0.0/configurations/rubocop/ruby.yml
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/4.0.0/configurations/rubocop/performance.yml
  - https://raw.githubusercontent.com/bkuhlmann/code_quality/4.0.0/configurations/rubocop/rspec.yml

